# Generated by Django 4.0.4 on 2022-05-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('titulo', models.CharField(max_length=300)),
                ('descricao', models.TextField()),
                ('link', models.CharField(max_length=300)),
            ],
        ),
    ]
