# Generated by Django 4.0.4 on 2022-07-20 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_destination'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LastName', models.CharField(max_length=50)),
                ('FirstName', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=2)),
                ('Age', models.IntegerField()),
            ],
        ),
    ]
