# Generated by Django 4.0.4 on 2022-09-21 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_friends'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('Apelido', models.CharField(max_length=50)),
                ('link_pagina_lusofona', models.URLField()),
                ('linkedin', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Cadeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadeira_nome', models.CharField(max_length=20)),
                ('ano', models.IntegerField()),
                ('topico', models.TextField()),
                ('semestre', models.SmallIntegerField()),
                ('ano_frequentado', models.IntegerField()),
                ('ects', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Licenciatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licenciatura_nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('Apelido', models.CharField(max_length=50)),
                ('link_pagina_lusofona', models.URLField()),
                ('linkedin', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Tfc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tfc_titulo', models.CharField(max_length=200)),
                ('tfc_descricao', models.TextField(blank=b'I01\n')),
                ('orientador', models.ForeignKey(blank=b'I01\n', null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.professor')),
                ('tfc_alunos', models.ForeignKey(blank=b'I01\n', null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.aluno')),
                ('tfc_licenciatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.licenciatura')),
            ],
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
        migrations.AddField(
            model_name='cadeira',
            name='licenciatura',
            field=models.ManyToManyField(to='portfolio.licenciatura'),
        ),
        migrations.AddField(
            model_name='cadeira',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.professor'),
        ),
    ]
